male(george).
male(spencer).
male(philip).
male(charles).
male(mark).
male(andrew).
male(edward).
male(william).
male(harry).
male(peter).
male(eugine).
male(james).

female(mum).
female(kydd).
female(elizabeth).
female(margaret).
female(diana).
female(anne).
female(sarah).
female(sophie).
female(zara).
female(beatrice).
female(louise).

isSpouse(george,mum).
isSpouse(spencer,kydd).
isSpouse(elizabeth,philip).
isSpouse(diana,charles).
isSpouse(anne,mark).
isSpouse(andrew,sarah).
isSpouse(edward,sophie).

areParents(george,mum,elizabeth).
areParents(george,mum,margaret).
areParents(spencer,kydd,diana).
areParents(elizabeth,philip,charles).
areParents(elizabeth,philip,anne).
areParents(elizabeth,philip,andrew).
areParents(elizabeth,philip,edward).
areParents(diana,charles,william).
areParents(diana,charles,harry).
areParents(anne,mark,peter).
areParents(anne,mark,zara).
areParents(andrew,sarah,beatrice).
areParents(andrew,sarah,eugine).
areParents(edward,sophie,louise).
areParents(edward,sophie,james).
